### ISSUE TITLE
Add a 'riding dirty' tracker

### ISSUE THREAD

**Issue by eebbesen** [eebbesen/freerider_api#6]
Identify which cars have internal/external cleanliness issues. Try to figure out if there's a pattern.
- [x] add `exterior` and `interior` to model
- [ ] provide endpoint for report
- [ ] allow caller to specify interior, exterior or both
- [ ] allow caller to specify time range (e.g. week, month, year)

```
$ bin/caruby2go v twincities | grep terior | sort | uniq
exterior:: GOOD
exterior:: UNACCEPTABLE
interior:: GOOD
interior:: UNACCEPTABLE
```
